### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by mikeyweigand** [CDCgov/polkapox#3]
CI not copied from gitlab. Need to modify/replace nf-core template defaults in `.github/workflows/`.  

See also #1

**Comment by kyleoconnell** [comment]
Not needed: (not yet run)
+ .github/workflows/awsfulltest.yml
+ .github/workflows/awstest.yml
+ 

Modified and should keep:
+ .github/workflows/branch.yml  (working)
+ .github/workflows/ci.yml (failing due to lack of test config)

Maybe keep, but probably should not:
+ .github/workflows/fix-linting.yml
+ .github/workflows/linting.yml
+ .github/workflows/linting_comment.yml

**Comment by kyleoconnell** [comment]
Need to add lighter linting workflow.

**Comment by kyleoconnell** [comment]
Modified and should keep:

.github/workflows/branch.yml (working)
.github/workflows/ci.yml (failing due to lack of test config)

Needs updating
+ Need to add a linting workflow, but deleted them all for now.
